
version: "3"
services:
  vendas_frontend:
    build: docker/vendasfrontend-docker/
    ports:
      - 8080:80
    volumes:
      - ./app/frontend:/var/www/frontend
    links:
      - rabbitmq
      - mysql
  redis:
    image: redis
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
    ports:
      - 3308:3306